CREATE TABLE [dbo].[Sessions]
(
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [CongressNumber] [int] NOT NULL,
    [SessionNumber] [int] NOT NULL,
    [Year] [int] NOT NULL,
    CONSTRAINT [PK_dbo.Sessions] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [Idx_Congress_Session] ON [dbo].[Sessions]
(
	[CongressNumber] ASC,
	[SessionNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO
