# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  BuildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      projects: "congress/congress.csproj"
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"

  - task: DotNetCoreCLI@2
    inputs:
      command: "test"
      projects: "congress.tests/congress.tests.csproj"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "congress_drop"

  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: "install"
      workingDir: "congressional-votes"

  - task: Npm@1
    displayName: "Build Angular"
    inputs:
      command: "custom"
      customCommand: "run build -- --prod"
      workingDir: "congressional-votes"

  - task: Npm@1
    displayName: "Run Angular Tests"
    inputs:
      command: "custom"
      customCommand: "run test"
      workingDir: "congressional-votes"

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: "angular"
      targetPath: "congressional-votes/dist"
